# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  kubeconfig:  # id of input
    description: 'kube secret'
    required: true
  
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
    # - ${{ inputs.who-to-greet }}
    # - '--name=${{ inputs.who-to-greet }}'
