on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: yarn    
      - name: deploy to playground
        id: deploy
        uses: ./
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}